version: 2
updates:
  - package-ecosystem: "npm"

    directory: "/"

    schedule:
      interval: "daily"

    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "security"
      - match:
          dependency_type: "production"
          update_type: "minor"
      - match:
          dependency_type: "development"
          update_type: "patch"